name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: URL="$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
             echo "URL=$URL" >> $GITHUB_ENV
      - name: Create pull request
        run: |
          curl \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d "{\"title\":\"Add deployment URLs\",\"body\":\"Preview URL: $URL \nProduction URL: https://dev-sec-ops-fawn.vercel.app\",\"head\":\"${{ github.ref }}\",\"base\":\"main\"}" \
